server:
  #address: localhost
  port: 7003
spring:
  application:
    name: hellospringboot
  datasource:
      druid:
          dest:
              type: com.alibaba.druid.pool.DruidDataSource
              driverClassName: com.mysql.jdbc.Driver
              #url: jdbc:mysql://10.20.65.161:3306/hellospringboot?useUnicode=true&characterEncoding=utf8
              #username: root
              #password: 5even@test2017
              url: jdbc:mysql://127.0.0.1:3306/hellospringboot?useUnicode=true&characterEncoding=utf8
              username: root
              password: 123015
              initialSize: 1
              minIdle: 3
              maxActive: 20
              # 配置获取连接等待超时的时间
              maxWait: 60000
              # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
              timeBetweenEvictionRunsMillis: 60000
              # 配置一个连接在池中最小生存的时间，单位是毫秒
              minEvictableIdleTimeMillis: 30000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              # 打开PSCache，并且指定每个连接上PSCache的大小
              poolPreparedStatements: true
              maxPoolPreparedStatementPerConnectionSize: 20
              # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
              filters: stat,wall,slf4j
              # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
              connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          yun:
              type: com.alibaba.druid.pool.DruidDataSource
              driverClassName: com.mysql.jdbc.Driver
              #url: jdbc:mysql://10.20.65.161:3306/f10_etl?useUnicode=true&characterEncoding=utf8
              #username: root
              #password: 5even@test2017
              url: jdbc:mysql://127.0.0.1:3306/f10_etl?useUnicode=true&characterEncoding=utf8
              username: root
              password: 123015
              initialSize: 1
              minIdle: 3
              maxActive: 20
              maxWait: 60000
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 30000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxPoolPreparedStatementPerConnectionSize: 20
              filters: stat,wall,slf4j
              connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  cache:
      type: REDIS
      cache-names: redis_cache , ehcache # 缓存的名字(可以不指定)
      redis:
        time-to-live: 60000  # 很重要，缓存的有效时间，以便缓存的过期（单位为毫秒）
  redis:
      #host: 10.20.65.161
      #password: hundsun123
      host: localhost
      password:
      port: 6379
      # 连接超时时间（毫秒）
      timeout: 10000
      jedis:
        pool:
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1


#mybatis-plus
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/springboot/hello/hellospringboot/dao/*/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: springboot.hello.hellospringboot.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: cn.jeefast.xxx
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'


##############全局配置项 异常配置#################
system:
  ###### 当异常出现时，使用json返回
  isAjax: true
  #######异常相关配置项#########
  exception:
    ######默认错误号############
    default-errorCode: 10000
    ######默认错误信息##########
    default-error-info: 系统罢工了,请等会再来
    ######默认错误状态#########
    default-status: 500
    ######扫描包路径,当 出现运行时异常时,提取此包下的堆栈信息,方便开发人员定位具体错误代码行###########
    basePackages: cn.winner
    ######异常错误号前缀配置,分为数据绑定,业务,系统 3类异常#######
    bind-exception-prefix: BIND-
    biz-exception-prefix: BIZ-
    system-exception-prefix: SYS-
  ####服务层参数验证相关配置##########
  validation:
    ####是否开启服务层参数验证,如果服务层单独部署需要开启次项########
    open-service-validation: true
  ######数据字典相关配置##########
  dictionary:
    ######当为找到字典项时是否抛出异常 默认false 表示不抛异常
    throw-exception-when-not-fund: false
    ######未找到时抛出的异常信息#######
    exception-message: "未找到字典项"
    ######未找的字典项时返回的默认信息#######
    not-fund-message: "未知"

logging:
  config: classpath:logback.xml

stock:
  url: http://hq.sinajs.cn/
  code: sh601003,sh601001,sh600570,sz000001

### 防篡改加签-签名密钥
shakey: LUTqZb3IkHjKcH3xjQcpqfZvWvNjQ4760KjZb3VBXmJ4Y9zwK5egrkIQK05DaCiq4vlxqAEvUzDTsl8vwlYNWJpozHxRjbSXr6gBcMxPtRbtPcLRkgwhgvD/3k054XnKFlmbQW5y716VSFkjLQnjY91c+HoAO4IiWpsYOUD+ZX4=

#图片保存地址
main-dir: D:\\software\\tomcat\\tomcat-8.5.34-x64\\webapps
#main-dir: /disk4/hellospringboot-view/tomcat-hellospringboot-view/webapps

#图片访问地址
visit-url: http://127.0.0.1:8081/
#visit-url: http://10.20.65.161:9527/

# 脚本路径
jmx-dir: /disk4/hellospringboot-view/testCase/

# 脚本运行结果 生成路径
jtl-dir: /disk4/hellospringboot-view/result/

